language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - datamuse/test_api.py
notifications:
    branch: master
    email:
        on_success: never
        on_failure: always
