language: python
python:
    - "3.5"
install:
    - pip install -r requirements-devel.txt
script:
    - tests/datamuse/test_api.py
notifications:
    branch: master
    email:
        on_success: never
        on_failure: always
